version: "3.1"
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    image: jude-backend
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    image: jude-frontend
    depends_on: 
      - backend
    volumes:
      - ./frontend/:/app
    ports:
      - "80:80"
