version: "3.1"
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend.dev
    image: jude-backend
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend.dev
    image: jude-frontend
    depends_on: 
      - backend
    volumes:
      - ./frontend/:/app
    ports:
      - "3000:80"
