FROM python:3.9
WORKDIR /app

# install python env
COPY backend/requirements.txt ./
RUN pip install -r ./requirements.txt

# install cron
RUN apt-get update && apt-get install -y cron

COPY backend/ ./

# run the gunicorn server
ENV FLASK_ENV production
EXPOSE 5000
CMD ["./backend_start.sh"]
